config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  get 'admin', to:'static_pages#admin', as: :admin
  get 'teacher', to:'static_pages#teacher', as: :teacher
  get 'csv_girls', to:'static_pages#csv_girls', as: :csv_girls
  get 'csv_adults', to:'static_pages#csv_adults', as: :csv_adults
  get 'csv_sessions', to:'static_pages#csv_sessions', as: :csv_sessions
  get 'csv_medications', to:'static_pages#csv_medications', as: :csv_medications
  get 'csv_dietary', to:'static_pages#csv_dietary', as: :csv_dietary
  get 'csv_gluten', to:'static_pages#csv_gluten', as: :csv_gluten
  get 'csv_release', to:'static_pages#csv_release', as: :csv_release
  get 'csv_units', to:'static_pages#csv_units', as: :csv_units
  get 'csv_troops', to:'static_pages#csv_troops', as: :csv_troops
  get 'csv_extras', to:'static_pages#csv_extras', as: :csv_extras
  get 'home', to:'static_pages#home', as: :home

  get '404', :to => 'static_pages#home'

  resources :girls
  resources :adults

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  include ApplicationHelper

  def home
  end

  def splash
    if user_signed_in?
      redirect_to :home and return
    end
  end

  def teacher
    if params[:q] != "yourock123"
      redirect_to :root, alert: "Sorry, teacher password was not correct." and return
    end
    redirect_to :home
  end

  def admin
  	bounce_nonadmin
  end

  def csv_girls
  	bounce_nonadmin
  	@girls = Girl.all.order(:last_name)
  	respond_to do |format|
  		format.html
  		format.csv {
  			headers['Content-Disposition'] = 'attachment; filename=girl-registrations-list.csv'
  			headers['Content-Type'] ||= 'text/csv'
  		}
  	end
  end

  def csv_adults
  	bounce_nonadmin
  	@adults = Adult.all.order(:last_name)
  	respond_to do |format|
  		format.html
  		format.csv {
  			headers['Content-Disposition'] = 'attachment; filename=adult-registrations-list.csv'
  			headers['Content-Type'] ||= 'text/csv'
  		}
    end
  end

  def csv_sessions
  	bounce_nonadmin
  	@girls = Girl.all.order(:last_name)
  	respond_to do |format|
  		format.html
  		format.csv {
  			headers['Content-Disposition'] = 'attachment; filename=sessions-list.csv'
  			headers['Content-Type'] ||= 'text/csv'
  		}
    end
  end

  def csv_medications
  	bounce_nonadmin
  	@girls = Girl.where(medications:true).all.order(:last_name)
  	respond_to do |format|
  		format.html
  		format.csv {
  			headers['Content-Disposition'] = 'attachment; filename=medications-list.csv'
  			headers['Content-Type'] ||= 'text/csv'
  		}
    end
  end

  def csv_dietary
    bounce_nonadmin
    @girls = Girl.where("length(dietary) > 0").all.order(:last_name)
    respond_to do |format|
      format.html
      format.csv {
        headers['Content-Disposition'] = 'attachment; filename=dietary-list.csv'
        headers['Content-Type'] ||= 'text/csv'
      }
    end
  end

  def csv_gluten
    bounce_nonadmin
    @girls = Girl.where(no_gluten:true).all.order(:last_name)
    respond_to do |format|
      format.html
      format.csv {
        headers['Content-Disposition'] = 'attachment; filename=gluten-list.csv'
        headers['Content-Type'] ||= 'text/csv'
      }
    end
  end

  def csv_release
    bounce_nonadmin
    @girls = Girl.where(release:false).all.order(:last_name)
    respond_to do |format|
      format.html
      format.csv {
        headers['Content-Disposition'] = 'attachment; filename=media-release-list.csv'
        headers['Content-Type'] ||= 'text/csv'
      }
    end
  end

  def csv_units
    bounce_nonadmin
    @girls = Girl.all.order(:level_id, :last_name)
    respond_to do |format|
      format.html
      format.csv {
        headers['Content-Disposition'] = 'attachment; filename=unit-list.csv'
        headers['Content-Type'] ||= 'text/csv'
      }
    end
  end

  def csv_troops
    bounce_nonadmin
    @girls = Girl.all.order(:troopnumber, :last_name)
    respond_to do |format|
      format.html
      format.csv {
        headers['Content-Disposition'] = 'attachment; filename=troop-list.csv'
        headers['Content-Type'] ||= 'text/csv'
      }
    end
  end

  def csv_extras
    bounce_nonadmin
    @girls = Girl.where(horseback:true).or(Girl.where(kayaking:true)).all.order(:last_name)
    respond_to do |format|
      format.html
      format.csv {
        headers['Content-Disposition'] = 'attachment; filename=extras-list.csv'
        headers['Content-Type'] ||= 'text/csv'
      }
    end
  end

private

  def bounce_nonadmin
  	unless user_signed_in? && current_user.is_admin?
  		redirect_to action: "home"
  	end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def format_for_csv(input)
		if input.nil?
			return "none"
		end
		input.gsub!(",", "")
		#input.sub!("&", "&amp;")
		input.sub!('""', "")
		input.length == 0 ? "none" : input
	end

	def yes_or_no(input)
		input ? "Y" : "N"
	end

	def sessions_for_particular_girl(girl)
		if girl.level.name == "Tenderheart"
			return nil
		end
		girl.sessions.each{ |x|
			sessions << x
		}
	end

	def session_if_one_exists(girl, slot)
		if (girl.nil? || girl.level.name == "Tenderheart")
			return nil
		end
		the_session = girl_session_for_particular_slot(girl,Slot.where(name:slot).first)
		if the_session.nil?
			return nil
		else
			return the_session.id
		end
	end

	def session_names_for_particular_girl(girl)
		girl.sessions.map {|x| format_for_csv(x.name)}
	end

	def girl_session_for_particular_slot(girl, slot)
		girl.sessions.each{ |x|
			if x.slot == slot
				return x
			end
		}
		return nil
	end

	def appropriate_sessions_for_level(level, slot)
		possibles = Slot.where(name:slot).first.sessions.where(level:level).all.to_a
		possibles.keep_if { |x| x.girls.count < x.capacity }
	end

	def adult_sessions()
		sessions_array = Session.all.collect { |x| [ x.name, x.id] }
		returned_array = Array.new
		sessions_array.each { |x|
			if returned_array.assoc(x[0]) == nil
				returned_array << x
			end
		}
		returned_array.collect!{ |x| x[1] }
		Session.find(returned_array)
	end

	def session_table_name(session)
		return_string = "#{session.name} (#{session.level.name}) -- #{pluralize(session.girls.count, "Girl")}"
		if session.girls.count >= session.capacity
			return_string << " -- SESSION FULL"
		end
		return_string
	end

	def what_is_in_slot(slot, girl)
		girl.sessions.each { |x|
			if x.slot.name == slot
				return x.name
			end
		}
		return "No choice"
	end

	def non_tenderheart_sessions(this_slot)
		Session.where(slot:Slot.where(name:this_slot).first).where.not(level:Level.where(name:"Tenderheart").first).all
	end

end

app/views/static_pages/_adults_listing.html.erb
<table class="table table-striped table-bordered tiny-text">
<tr>
	<th>Adult</th>
	<th>Address</th>
	<th>Phone</th>
	<th>Troop</th>
	<th>Troop Contact</th>
	<th>Dietary Restrictions</th>
	<th>CPR</th>
	<th>First Aid</th>
	<th>T-Shirt Size</th>
	<th>Helping With</th>
</tr>
<% Adult.all.order(:last_name).each { |x| %>
<tr>
	<td>
		<%= "#{x.first_name} #{x.last_name}".titleize %>
	</td>
	<td>
		<%= "#{x.address}" %>
	</td>
	<td>
		<%= "#{x.phone}" %>
	</td>
	<td>
		<%= "#{x.troopnumber}" %>
	</td>
	<td>
		<%= "#{x.troopcontact}" %>
	</td>
	<td>
		<%= "#{x.dietary}" %>
	</td>
	<td>
		<%= "#{x.cpr ? "Yes" : "No"}" %>
	</td>
	<td>
		<%= "#{x.first_aid ? "Yes" : "No"}" %>
	</td>
	<td>
		<%= "#{x.tshirt.nil? ? '?' : x.tshirt.name}"%>
	</td>
	<td>
		<%= "#{x.sessions.first.name}" %>
	</td>
</tr>
<% } %>
</table>

app/views/static_pages/_footer_matter.html.erb
<div class="row footer-matter">
	<div class="col-md-11">
	<p class="questions">Questions about registration? Email <a href="mailto:ahgcampgtr@gmail.com">Camp Director</a>.<p>
	<p class="copyright">Camp registration information will be maintained in accordance with the scouting organization's privacy policies.</p>
	<p class="copyright">Developed, and license to use web application donated by, Idaria Software.
	For questions about web application, please contact <a href="mailto:abwinkler999+ahg@gmail.com">Idaria Software</a>.</p>
	</div>
</div>

app/views/static_pages/_girlsblock.html.erb
<% @admin_display = false %>
<div id="girls_list_block">
<h3>Your Girls Registered For Greater Than Rubies Summer Camp 2017</h3>
<%= render "girl_table", admin_display: false %>
<% if at_camp_limit && !current_user.is_admin %>
  <h5>(Sorry, Greater Than Rubies Summer Camp 2017 has hit the camp registration limit.  If you wish, please email <a href="mailto:ahgcampgtr@gmail.com">the Camp Director</a> to be placed on the waiting list.)</h5>
<% else %>
  <% if at_tenderheart_limit && !current_user.is_admin %>
    <h5>(Sorry, Greater Than Rubies Summer Camp 2017 has hit the registration limit for Tenderhearts.  If you wish, please email <a href="mailto:ahgcampgtr@gmail.com">the Camp Director</a> to be placed on the waiting list.)</h5>
  <% else %>
    <%= link_to "Register A Tenderheart", new_girl_path(level: "Tenderheart"), class: "btn btn-success" %>
  <% end %>
  <%= link_to "Register An Explorer", new_girl_path(level: "Explorer"), class: "btn btn-success" %>
  <%= link_to "Register A Pioneer/Patriot", new_girl_path(level: "Pioneer/Patriot"), class: "btn btn-success" %>
<% end %>
</div>

app/views/static_pages/_parentblock.html.erb
<div class="parentblock">
	<% unless current_user.adult %>
		<h3>(You have not registered an adult for Greater Than Rubies Summer Camp 2017.)</h3>
		<%= link_to "Register Adult to Attend", new_adult_path, class: "btn btn-success" %>
	<% else %>
		<% the_adult = current_user.adult %>
		<h3>You are Attending Greater Than Rubies Summer Camp 2017!</h3>
		<div id="attendeeinfo" class="well">
			<h3><strong><%=	"#{the_adult.first_name} #{the_adult.last_name}".titleize %></strong></h3>
			<div class="row">
				<div class="col-md-6">
					<strong><%= "Phone:" %></strong>  <%= " #{the_adult.phone}" %><br />
					<strong><%= "Mailing address:" %></strong>  <%= " #{the_adult.address}" %> <br />
					<strong><%= "Troop:" %></strong>  <%= " #{the_adult.troopnumber}" %><br />
					<strong><%= "Troop Coordinator's Name:" %></strong>  <%= " #{the_adult.troopcontact}" %><br />
					<strong><%= "Troop Coordinator's Email:" %></strong>  <%= " #{the_adult.troopcontact_email}" %><br />
					<strong><%= "Dietary restrictions:" %></strong>  <%= " #{the_adult.dietary}" %><br />
				</div>
				<div class="col-md-6">
					<strong><%= "CPR trained?" %></strong>  <%= "  #{the_adult.cpr? ? "Y" : "N"}" %><br />
					<strong><%= "First aid trained?" %></strong>  <%= "  #{the_adult.cpr? ? "Y" : "N"}" %><br />
					<strong><%= "T-shirt size:" %></strong>  <%= " #{the_adult.tshirt.nil? ? '?' : the_adult.tshirt.name}" %><br />
					<strong><%= "Helping With:" %></strong>  <%= " #{the_adult.sessions.first.name}" %><br />
				</div>
			</div>
		</div>
		<p>
		<%= link_to "Cancel Adult Registration", adult_path(the_adult), method: :delete, data: { confirm: "Are you certain you want to cancel your registration?" }, class: "btn btn-danger" %>
		</p>
	<% end %>
</div>

app/views/static_pages/_reports.html.erb
<div class="row">
  <div class="col-md-5">
    <ul>
      <li>
        <%= link_to 'Session Sign-ups', csv_sessions_path(format: :csv) %>
      </li>
      <li>
        <%= link_to 'List of Girls', csv_girls_path(format: :csv)%>
      </li>
      <li>
        <%= link_to 'List of Girls by Units', csv_units_path(format: :csv)%>
      </li>
      <li>
        <%= link_to 'List of Girls by Troops', csv_troops_path(format: :csv)%>
      </li>
      <li>
        <%= link_to 'List of Adults', csv_adults_path(format: :csv)%>
      </li>
    </ul>
  </div>
  <div class="col-md-5">
    <ul>
      <li>
        <%= link_to 'List of Girls with Medications', csv_medications_path(format: :csv)%>
      </li>
      <li>
        <%= link_to 'List of Girls with Dietary Restrictions', csv_dietary_path(format: :csv)%>
      </li>
      <li>
        <%= link_to 'List of Girls with Gluten Sensitivity', csv_gluten_path(format: :csv)%>
      </li>
      <li>
        <%= link_to 'List of Girls Refusing Media Permission', csv_release_path(format: :csv)%>
      </li>
      <li>
        <%= link_to 'List of Girls Attending Horse Experience or Kayaking', csv_extras_path(format: :csv)%>
      </li>
    </ul>
  </div>
</div>

app/views/static_pages/admin.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1 buttons_row reports_box">
		<h3>Downloadable Reports</h3>
		<%= render "reports" %>
		<%= link_to 'Back to Main Page', home_path, class: "btn btn-primary" %>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<h4><%= Adult.all.count %> Registered Adults</h4>
		<%= render "adults_listing" %>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<h4><%= Girl.all.count %> Registered Girls</h4>
		<%= render "girl_table", admin_display:true %>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<h3>Sessions Signups</h3>
		<%= render "sessions_table", admin_display:true %>
	</div>
</div>

app/views/static_pages/csv_adults.csv.erb
<% headers = ['Last Name', 'First Name', 'Address', 'Phone', 'Troop', 'Troop Contact', 'Troop Contact Email', 'Dietary Requirements',
	'CPR', 'First Aid', 'T-Shirt'] %>
<%= CSV.generate_line headers %>
<% @adults.each do |adult| %>
	<%= CSV.generate_line([adult.last_name, adult.first_name, format_for_csv(adult.address), format_for_csv(adult.phone), format_for_csv(adult.troopnumber.upcase), format_for_csv(adult.troopcontact), format_for_csv(adult.troopcontact_email), format_for_csv(adult.dietary), yes_or_no(adult.cpr),	yes_or_no(adult.first_aid), adult.tshirt.name].flatten, encoding:"utf-8") %>
<% end %>

app/views/static_pages/csv_dietary.csv.erb
<% headers = ['Last Name', 'First Name', 'Troop', 'Dietary Restrictions', 'Parent Cell', 'Other Cell', 'Parent Email'] %>
<%= CSV.generate_line headers %>
<% @girls.each do |girl| %>
<%= CSV.generate_line([girl.last_name, girl.first_name, format_for_csv(girl.troopnumber.upcase),
	format_for_csv(girl.dietary), format_for_csv(girl.parentcell),
	 format_for_csv(girl.othercell), girl.user.email].flatten,
	encoding:"utf-8") %>
<% end %>

app/views/static_pages/csv_girls.csv.erb
<% headers = ['Last Name', 'First Name', 'DOB', 'Level', 'Troop', 'Dietary Requirements',
	'Bringing Medications', 'Gluten Sensitive', 'Grade Fall 2015', 'Parent Cell', 'Other Cell', 'T-Shirt', 'Horse Experience', 'Kayaking', 'Photo OK',
	'Session A', 'Session B', 'Session C', 'Session D'] %>
<%= CSV.generate_line headers %>
<% @girls.each do |girl| %>
<%= CSV.generate_line([girl.last_name, girl.first_name, format_for_csv(girl.dob), girl.level.name, format_for_csv(girl.troopnumber.upcase), format_for_csv(girl.dietary),
	yes_or_no(girl.medications), yes_or_no(girl.no_gluten), format_for_csv(girl.fallgrade), format_for_csv(girl.parentcell),
	 format_for_csv(girl.othercell), girl.tshirt.name, yes_or_no(girl.horseback), yes_or_no(girl.kayaking), yes_or_no(girl.release), session_names_for_particular_girl(girl)].flatten,
	encoding:"utf-8") %>
<% end %>

app/views/static_pages/csv_gluten.csv.erb
<% headers = ['Last Name', 'First Name', 'Troop', 'No Gluten?', 'Parent Cell', 'Other Cell', 'Parent Email'] %>
<%= CSV.generate_line headers %>
<% @girls.each do |girl| %>
<%= CSV.generate_line([girl.last_name, girl.first_name, format_for_csv(girl.troopnumber.upcase),
	yes_or_no(girl.no_gluten), format_for_csv(girl.parentcell),
	 format_for_csv(girl.othercell), girl.user.email].flatten,
	encoding:"utf-8") %>
<% end %>

app/views/static_pages/csv_units.csv.erb
<% headers = ['Last Name', 'First Name', 'DOB', 'Level', 'Troop', 'Dietary Requirements',
	'Bringing Medications', 'Gluten Sensitive', 'Grade Fall 2015', 'Parent Cell', 'Other Cell', 'T-Shirt', 'Horse Experience', 'Kayaking', 'Photo OK',
	'Session A', 'Session B', 'Session C', 'Session D'] %>
<%= CSV.generate_line headers %>
<% @girls.each do |girl| %>
<%= CSV.generate_line([girl.last_name, girl.first_name, format_for_csv(girl.dob), girl.level.name, format_for_csv(girl.troopnumber.upcase), format_for_csv(girl.dietary),
	yes_or_no(girl.medications), yes_or_no(girl.no_gluten), format_for_csv(girl.fallgrade), format_for_csv(girl.parentcell),
	 format_for_csv(girl.othercell), girl.tshirt.name, yes_or_no(girl.horseback), yes_or_no(girl.kayaking), yes_or_no(girl.release), session_names_for_particular_girl(girl)].flatten,
	encoding:"utf-8") %>
<% end %>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
<div class="row mainblock">
	<div class="row">
		<div class="col-md-12">
		<%= render "parentblock" %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<%= render "girlsblock" %>
		</div>
	</div>
</div>
<% else %>
<div id="please_sign_in">
	<div class="row">
		<div class="col-md-12">
			<div class="maingraphic", style="margin-left:auto; margin-right:auto; width:60%">
				<%= image_tag("gtr.png", width:"40%") %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<h3>Sorry, Greater Than Rubies Summer Camp 2017 has hit the camp registration limit.</h3>
		</div>
</div>
<% end %>

app/views/static_pages/regular_home.html.erb
<% if user_signed_in? %>
<div class="row mainblock">
	<div class="row">
		<div class="col-md-12">
		<%= render "parentblock" %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<%= render "girlsblock" %>
		</div>
	</div>
</div>
<% else %>
<div id="please_sign_in">
	<div class="row">
		<div class="col-md-12">
			<div class="maingraphic", style="margin-left:auto; margin-right:auto; width:60%">
				<%= image_tag("gtr.png", width:"60%") %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-9">
			<h3>Get started registering for Greater Than Rubies Summer Camp 2017:</h3>
		</div>
		<div class="col-md-3">
			<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-lg login-buttons" %>
		</div>
</div>
<% end %>

app/views/static_pages/splash.html.erb
<div id="please_sign_in">
	<div class="row">
		<div class="col-md-9">
			<h3 style="line-height:1.2">Registration for Greater Than Rubies Summer Camp 2017 is currently limited to teachers.</h3>
		</div>
		<div class="col-md-3">
			<%= form_tag("/teacher", method: "get") do %>
			  <%= label_tag(:q, "Password:") %>
			  <%= text_field_tag(:q) %>
			  <%= submit_tag("Enter", class:"btn btn-primary btn-lg login-buttons") %>
			<% end %>
		</div>
</div>